name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Copy .env
      run: cp .env.example .env
    - name: Install Dependencies
      run: composer install --prefer-dist --no-scripts --no-progress --no-interaction --ignore-platform-reqs
    # Dockerコンテナを起動
    - name: Start Containers
      run: ./vendor/bin/sail up -d
    # 以降のステップも同様にsail execを使用してコンテナ内で実行
    - name: Generate Key
      run: ./vendor/bin/sail exec laravel.test php artisan key:generate
    - name: Directory Permissions
      run: ./vendor/bin/sail exec laravel.test chmod -R 777 storage bootstrap/cache
    - name: Test MySQL Connection
      run: ./vendor/bin/sail exec laravel.test mysql -h mysql -u sail -ppassword -e 'SHOW DATABASES;'
    - name: Create Database
      run: |
        ./vendor/bin/sail exec laravel.test touch database/database.sqlite
        ./vendor/bin/sail exec laravel.test php artisan migrate
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.2'  # こちらのバージョンはプロジェクトに合わせて変更してください
    - name: Install Node Dependencies
      run: npm install
    # テスト実行
    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ./vendor/bin/sail exec laravel.test vendor/bin/phpunit
