name: Laravel Sail Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp .env.example .env
    - name: Build and up docker containers
      run: ./vendor/bin/sail up -d
    - name: Install Composer Dependencies
      run: ./vendor/bin/sail composer install
    - name: Generate key
      run: ./vendor/bin/sail artisan key:generate
    - name: Run Migrations
      run: ./vendor/bin/sail artisan migrate
    - name: Run Tests
      run: ./vendor/bin/sail artisan test
